### ISSUE TITLE
git hashes are too long

### ISSUE THREAD

**Issue by emaste** [FreeBSDFoundation/jenkins-tinderbox#7]
We should display short hashes (12 chars) to better fit in the table

![image](https://user-images.githubusercontent.com/1034582/128642456-31b5dfe6-7614-4984-b389-df0216c8e85d.png)

**Comment by jrtc27** [comment]
That comes from the description field of the jobs in question. I don't know if that means we should shorten what we set the field to in Jenkins or assume it's a git hash here and truncate it.

**Comment by lwhsu** [comment]
It's fine to assume that the build description field is a git hash because we intentionally set that in our Jenkins configuration.
https://github.com/freebsd/freebsd-ci/blob/master/jjb/macro.yaml#L15-L19

**Comment by jrtc27** [comment]
(For the build jobs you could query `changeSet[items[id]{0}]` instead of `description`, but that won't extend to test jobs as those currently report a change list based on whatever changed since they last ran but will use the specific artifacts from the build jobs and set their description to that job's hash)

**Comment by lwhsu** [comment]
Right, for test jobs it is actually a bug, or a regression of switching to git. In svn era, we propagate svn revision number from upstream job, and the downstream job will check out the same revision to show the correct change list. I'm still searching for the fix of this.

**Comment by jrtc27** [comment]
We do get the right GIT_COMMIT environment variable from the trigger and fetch the right job, just the Jenkins Changes list doesn't know that we're using a specific commit, it just knows about the branch.

**Comment by lwhsu** [comment]
That's exactly the issue, the svn plugin honors the SVN_REVISION env from the trigger of upstream and use it to check out the specified revision, then shows the change list. However, the git plugin just pulls the latest HEAD of the branch.

I'm not sure if it is due to my configuration error.
